name: utk-genomics-core
channels:
  - conda-forge
  - bioconda
dependencies:
  - biopython
  - ca-certificates
  - certifi
  - ipykernel
  - jinja2
  - lxml
  - mamba
  - multiqc
  - nbconvert
  - numpy
  - openpyxl
  - openssl
  - pandas
  - python=3.13
  - sample-sheet
  - scikit-learn
  - scipy
  - simple_slurm
